Copyright Jana Schaich Borg/Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) 번역/보충설명: 황수민

# MySQL 연습문제 4: 데이터를 요약하기

지난 연습문제에서는 데이터를 Export하고 편집하는 연습을 했는데요, 이번 연습문제에서는 SQL을 사용해서 데이터의 모든 열과 행을 출력하지 않고 정보를 요약하는 것을 배울 것입니다. 데이터를 요약하는 것을 익히면 실제로 업무를 할 때 도움이 될 거에요 :)  

다음은 가장 자주 쓰이는 SQL 함수입니다. AVG (평균값), COUNT (총 몇개의 행이 있는지 센 값), MAX (최고값), MIN (최소값) 그리고 SUM (합계)입니다. 

<img src="https://duke.box.com/shared/static/bc3yclxtwmv8dffis09hwsvskx18u1mc.jpg" width=400 alt="AGGREGATE FUNCTIONS" />

특히 COUNT와 SUM은 매우 자주 사용하는데요, 제가 회사에서 쓰는 쿼리들의 대부분도 이 두 집계 함수를 써서 요약합니다. 

COUNT는 수치 데이터, 문자열을 불문하고 모든 유형의 데이터에서 사용할 수 있는 유일한 집계 함수입니다. 하지만 AVG (평균), MAX (가장 큰 값), MIN (가장 작은 값) 그리고 SUM (합)은 수치 데이터에만 사용할 수 있습니다.

우선 COUNT 함수를 자세히 살펴볼까요? 


## 1. COUNT 함수

** 먼저 SQL 라이브러리와 Dognition 데이터베이스를 로드하고 dognition을 기본 데이터베이스로 설정할게요. **

그러기 위해서는 다음 코드를 실행하면 됩니다 :) 

```python
%load_ext sql
%sql mysql://studentuser:studentpw@mysqlserver/dognitiondb
%sql USE dognitiondb
```

In [1]:
%load_ext sql
%sql mysql://studentuser:studentpw@localhost/dognitiondb
%sql USE dognitiondb

 * mysql://studentuser:***@localhost/dognitiondb
0 rows affected.

[]

다음의 쿼리를 실행하면 dogs 테이블에 모든 breed(품종)이 출력됩니다.  

```mySQL
SELECT breed
FROM dogs 
```

Jupyter의 출력 결과가 35050 개의 행이 "affected" 됐다고 하는 것을 보면 쿼리의 출력 결과에 35050개의 행이 있음을 알 수 있습니다. (Jupyter에서는 1000개의 행의 제한이 있어서 우선 1000개의 행만 출력해줍니다)

** 이제 한번 다음의 쿼리를 직접 실행 해보세요 : **

```mySQL
SELECT COUNT(breed)
FROM dogs 
```

In [9]:
%sql SELECT COUNT(breed)FROM dogs

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(35050,)]

COUNT는 해당 열에 (예를 들면 breed에) 몇개의 값이 있는지 출력합니다. COUNT를 사용하면 데이터를 모두 출력하지 않고 몇개의 행이 있는지 알아볼 수 있습니다. 

그리고 연습 문제 3에서 배운 DISTINCT절을 COUNT와 같이 사용하면 해당 열에 고유의 값이 몇 개가 있는지 출력할 수 있습니다. 하지만 DISTINCT절은 괄호 안에 넣어야 하는 것을 잊지 마세요. 예를 들면 다음의 쿼리를 실행하면 품종 (breed)열에 몇 개의 고유 값이 있는지 출력할 수 있습니다. 

```SQL
SELECT COUNT(DISTINCT breed)
  FROM dogs
```

만약에 몇 마리의 고유한 개가 테스트를 적어도 한번 완료했는지 알고 싶다면 어떻게 해야할까요?

complete_tests 테이블의 데이터는 테스트가 완료되야만 생성되기 때문에 complete_tests 테이블에 있는 개들은 (Dog-Guid) 적어도 하나의 테스트는 완료했다고 볼 수 있습니다. 그리고 열의 이름이 (예를 들면 Dog_guid) 괄호 안에 들어가 있으면 미확정 값 (NULL)은 제외되고, 세어지지 않습니다. 따라서 몇마리의 고유한 개가 테스트를 적어도 한번 완료했는지 알고 싶으면 다음 쿼리를 실행하면 됩니다:

```SQL
SELECT COUNT(DISTINCT Dog_Guid)
  FROM complete_tests
```

** 질문 1 : 위의 쿼리를 WHERE절과 함께 사용해서 2014년 3월 1일 이후에 테스트를 완료 한 개는 몇마리가 있는지 알아보세요 (정담은 13,289행입니다). **

In [15]:
%sql SELECT COUNT(DISTINCT Dog_Guid) FROM complete_tests WHERE created_at > "2014-03-01";

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(13289,)]

** 질문 2 : 두 번째 차이점을 알려면 COUNT (\*)를 사용하여 dogs 테이블의 행수를 계산하십시오. 여기서 주의해야 할 점은 COUNT뒤에 공백이 없이 (\*)를 명시해야 합니다. **

In [16]:
%sql SELECT COUNT(*) FROM dogs;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(35050,)]

** 질문 3 : 이제 dogs 테이블의 제외 (exclude)열에 있는 행의 수를 계산하십시오. **

In [19]:
%sql SELECT COUNT(exclude) FROM dogs;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(1025,)]

COUNT (\*)와 COUNT(열 이름)의 차이  

1. DISTINCT는 COUNT (\*)와 함께 사용할 수 없음
2. COUNT(열 이름)은 NULL값을 제외하고 계산하나, COUNT (\*)은 NULL값을 포함함

** 질문 4 : dogs 테이블에 제외 (exclude)가 된 행이 몇 개가 있습니까? 답은 853입니다 (힌트: exclude가 된 값을 찾으려면 exclude열의 값을 잘 살펴보세요 )**

In [27]:
%sql SELECT SUM(exclude) FROM dogs;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(Decimal('853'),)]

## 2. SUM 함수

첫번째 쿼리의 결과가 
```mySQL
SELECT COUNT(exclude) 
FROM dogs
```
두번째 쿼리의 결과보다 훨씬 적다는 것은 
```mySQL
SELECT COUNT(*)
FROM dogs
```

바로 exclude열에 미확정 값 (NULL)이 많다는 것을 의미. 

ISNULL(첫번째 열, 두번째 열)이면 첫번째 열의 값이 미확정 (NULL)이면 두번째 열의 값으로 출력하라는 의미

ISNULL은 미확정 값 (NULL)이 있는 행에 1을 반환하게 하고 미확정 값이 아닌 행에는 0을 반환하게 하는 논리 함수.ISNULL (exclude) 구문을 SUM 안에 넣으면 미확값이 총 몇 개가 있는지 출력.

```mySQL
SELECT SUM(ISNULL(exclude))
FROM dogs
```

** dogs테이블의 exclude열의 미확정 값 (NULL)이 몇개가 있는지 계산해보십시오 : **

In [28]:
%sql SELECT SUM(ISNULL(exclude)) FROM dogs;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(Decimal('34025'),)]

## 3. AVG, MIN과 MAX 함수

AVG (평균), MAX (최고값), MIN (최소값)은 SUM (합계)과 비슷하게 작용함. 

** 질문 5 : "Memory versus Pointing" 게임에 평균, 최소 및 최대 등급 (rating)은 무엇입니까? (답은 각각 3.5584, 0 및 9이어야합니다.) **

In [31]:
%sql SELECT test_name, AVG(rating) AS AVG_rating, MIN(rating) AS MIN_rating, MAX(rating) AS MAX_rating FROM reviews WHERE test_name="Memory versus Pointing";

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[('Memory versus Pointing', Decimal('3.5584'), 0, 9)]

In [40]:
%sql SELECT test_name, AVG(rating),MIN(rating),MAX(rating) FROM reviews GROUP BY test_name ;

 * mysql://studentuser:***@localhost/dognitiondb
40 rows affected.

[('1 vs 1 Game', Decimal('3.9206'), 0, 9),
 ('3 vs 1 Game', Decimal('4.2857'), 0, 9),
 ('5 vs 1 Game', Decimal('3.9272'), 0, 9),
 ('Arm Pointing', Decimal('4.2153'), 0, 9),
 ('Cover Your Eyes', Decimal('2.6741'), 0, 9),
 ('Delayed Cup Game', Decimal('3.3514'), 0, 9),
 ('Different Perspective', Decimal('2.7647'), 0, 7),
 ('Expression Game', Decimal('4.0000'), 0, 9),
 ('Eye Contact Game', Decimal('2.9372'), 0, 9),
 ('Eye Contact Warm-up', Decimal('0.9632'), 0, 9),
 ('Foot Pointing', Decimal('4.0093'), 0, 9),
 ('Impossible Task Game', Decimal('3.0965'), 0, 9),
 ('Impossible Task Warm-up', Decimal('0.2174'), 0, 5),
 ('Inferential Reasoning Game', Decimal('4.5223'), 0, 9),
 ('Inferential Reasoning Warm-up', Decimal('4.3066'), 0, 9),
 ('Memory versus Pointing', Decimal('3.5584'), 0, 9),
 ('Memory versus Smell', Decimal('4.2623'), 0, 9),
 ('Navigation Game', Decimal('2.9841'), 0, 9),
 ('Navigation Learning', Decimal('2.0303'), 0, 9),
 ('Navigation Warm-up', Decimal('1.9805'), 0, 9),
 ('Numerosity Warm-Up', Decimal('2.6173'), 0, 9),
 ('One Cup Warm-up', Decimal('1.3693'), 0, 9),
 ('Physical Reasoning Game', Decimal('3.8492'), 0, 9),
 ('Physical Reasoning Warm-up', Decimal('1.6625'), 0, 9),
 ('Self Control Game', Decimal('3.8519'), 0, 9),
 ('Shaker Game', Decimal('4.6667'), 0, 9),
 ('Shaker Warm-Up', Decimal('2.1818'), 0, 9),
 ('Shared Perspective', Decimal('3.2778'), 0, 8),
 ('Slide', Decimal('4.5111'), 0, 9),
 ('Smell Game', Decimal('4.2857'), 0, 9),
 ('Stair Game', Decimal('4.2857'), 0, 9),
 ('Switch', Decimal('5.5676'), 0, 9),
 ('Treat Warm-up', Decimal('0.7909'), 0, 9),
 ('Turn Your Back', Decimal('3.1293'), 0, 9),
 ('Two Cup Warm-up', Decimal('1.6737'), 0, 9),
 ('Warm-Up', Decimal('1.2020'), 0, 9),
 ('Watching', Decimal('2.4594'), 0, 9),
 ('Watching - Part 2', Decimal('2.6570'), 0, 9),
 ('Yawn Game', Decimal('2.8477'), 0, 9),
 ('Yawn Warm-up', Decimal('2.0035'), 0, 9)]

** 질문 6 : exam_answers 테이블에 있는 각각의 테스트를 완료하는 데 걸린 시간 (분)은 어떻게 됩니까? 출력되는 기간의 열에 "Duration"이라는 임시 이름을 붙여주세요. **

In [11]:
%sql SELECT * FROM exam_answers LIMIT 100;

 * mysql://studentuser:***@localhost/dognitiondb
100 rows affected.

[(537, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 3, 58, 13), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (538, 'Emotions', 'Emotions', 'question', datetime.datetime(2013, 2, 5, 3, 58, 31), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (539, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 3, 59, 3), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (540, 'Perception', 'Perception', 'question', datetime.datetime(2013, 2, 5, 3, 59, 10), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (541, 'Recall', 'Recall', 'question', datetime.datetime(2013, 2, 5, 3, 59, 22), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (542, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 3, 59, 36), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (543, 'Puzzles', 'Puzzles', 'question', datetime.datetime(2013, 2, 5, 3, 59, 41), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (544, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 0), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (545, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 0, 16), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (546, 'Partnership', 'Partnership', 'question', datetime.datetime(2013, 2, 5, 4, 0, 35), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (547, 'Emotions', 'Emotions', 'question', datetime.datetime(2013, 2, 5, 4, 0, 46), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (548, 'Perception', 'Perception', 'question', datetime.datetime(2013, 2, 5, 4, 0, 54), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (549, 'Obedience', 'Obedience', 'question', datetime.datetime(2013, 2, 5, 4, 1, 1), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (550, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 4, 1, 15), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (551, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 4, 1, 40), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (552, 'Puzzles', 'Puzzles', 'question', datetime.datetime(2013, 2, 5, 4, 2, 2), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (553, 'Recall', 'Recall', 'question', datetime.datetime(2013, 2, 5, 4, 2, 30), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (554, 'Obedience', 'Obedience', 'question', datetime.datetime(2013, 2, 5, 4, 3), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (555, 'Perception', 'Perception', 'question', datetime.datetime(2013, 2, 5, 4, 3, 29), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (556, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 3, 37), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (557, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 3, 48), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (558, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 3, 56), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (559, 'Puzzles', 'Puzzles', 'question', datetime.datetime(2013, 2, 5, 4, 4, 7), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (560, 'Excitability', 'Excitability', 'question', datetime.datetime(2013, 2, 5, 4, 5, 31), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (561, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 4, 5, 47), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (562, 'Partnership', 'Partnership', 'question', datetime.datetime(2013, 2, 5, 4, 5, 57), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (563, 'Recall', 'Recall', 'question', datetime.datetime(2013, 2, 5, 4, 6, 6), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (564, 'Emotions', 'Emotions', 'question', datetime.datetime(2013, 2, 5, 4, 6, 30), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (565, 'Obedience', 'Obedience', 'question', datetime.datetime(2013, 2, 5, 4, 7, 38), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (566, 'Emotions', 'Emotions', 'question', datetime.datetime(2013, 2, 5, 4, 8, 58), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (567, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 4, 9, 5), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (568, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 9, 40), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (569, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 9, 44), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (570, 'Partnership', 'Partnership', 'question', datetime.datetime(2013, 2, 5, 4, 10, 3), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (571, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 10, 11), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (572, 'Perception', 'Perception', 'question', datetime.datetime(2013, 2, 5, 4, 10, 16), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (573, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 10, 26), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (574, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 11, 12), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (575, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 11, 21), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (576, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 11, 34), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (577, 'Recall', 'Recall', 'question', datetime.datetime(2013, 2, 5, 4, 11, 40), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (578, 'Perception', 'Perception', 'question', datetime.datetime(2013, 2, 5, 4, 11, 54), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (579, 'Excitability', 'Excitability', 'question', datetime.datetime(2013, 2, 5, 4, 12, 20), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (580, 'Puzzles', 'Puzzles', 'question', datetime.datetime(2013, 2, 5, 4, 12, 28), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (581, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 12, 49), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (582, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 13, 5), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (583, 'Excitability', 'Excitability', 'question', datetime.datetime(2013, 2, 5, 4, 13, 14), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (584, 'Partnership', 'Partnership', 'question', datetime.datetime(2013, 2, 5, 4, 13, 30), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (585, 'Partnership', 'Partnership', 'question', datetime.datetime(2013, 2, 5, 4, 13, 55), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (586, 'Emotions', 'Emotions', 'question', datetime.datetime(2013, 2, 5, 4, 14, 2), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (587, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 4, 14, 14), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (588, 'Excitability', 'Excitability', 'question', datetime.datetime(2013, 2, 5, 4, 14, 22), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (589, 'Excitability', 'Excitability', 'question', datetime.datetime(2013, 2, 5, 4, 14, 40), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (590, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 15, 4), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (591, 'Puzzles', 'Puzzles', 'question', datetime.datetime(2013, 2, 5, 4, 15, 10), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (592, 'Recall', 'Recall', 'question', datetime.datetime(2013, 2, 5, 4, 15, 38), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (593, 'Obedience', 'Obedience', 'question', datetime.datetime(2013, 2, 5, 4, 15, 56), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (594, 'Obedience', 'Obedience', 'question', datetime.datetime(2013, 2, 5, 4, 16, 2), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (595, 'Excitability', 'Excitability', 'question', datetime.datetime(2013, 2, 5, 4, 16, 18), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (596, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 16, 27), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (597, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 16, 36), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (598, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 16, 55), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (599, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 17, 2), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (600, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 17, 20), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (601, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 17, 27), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (602, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 4, 17, 43), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (603, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 18, 6), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (604, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 18, 15), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (605, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 18, 21), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (606, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 18, 31), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (607, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 4, 18, 44), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (608, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 4, 18, 50), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (609, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 19, 11), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (610, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 19, 20), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (611, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 19, 26), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (612, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 4, 19, 32), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (613, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 4, 19, 53), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (614, 'Excitability', 'Excitability', 'question', datetime.datetime(2013, 2, 5, 4, 20, 2), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (615, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 4, 20, 24), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b'),
 (537, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 15, 35, 28), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (538, 'Emotions', 'Emotions', 'question', datetime.datetime(2013, 2, 5, 15, 35, 38), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (539, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 15, 35, 47), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (540, 'Perception', 'Perception', 'question', datetime.datetime(2013, 2, 5, 15, 35, 54), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (541, 'Recall', 'Recall', 'question', datetime.datetime(2013, 2, 5, 15, 36, 1), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (542, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 15, 36, 10), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (543, 'Puzzles', 'Puzzles', 'question', datetime.datetime(2013, 2, 5, 15, 36, 24), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (544, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 15, 36, 33), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (545, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 5, 15, 36, 37), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (546, 'Partnership', 'Partnership', 'question', datetime.datetime(2013, 2, 5, 15, 36, 42), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (547, 'Emotions', 'Emotions', 'question', datetime.datetime(2013, 2, 5, 15, 36, 48), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (548, 'Perception', 'Perception', 'question', datetime.datetime(2013, 2, 5, 15, 36, 54), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (549, 'Obedience', 'Obedience', 'question', datetime.datetime(2013, 2, 5, 15, 36, 59), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (550, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 15, 37, 8), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (551, 'Attachment', 'Attachment', 'question', datetime.datetime(2013, 2, 5, 15, 37, 13), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (552, 'Puzzles', 'Puzzles', 'question', datetime.datetime(2013, 2, 5, 15, 37, 20), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (553, 'Recall', 'Recall', 'question', datetime.datetime(2013, 2, 5, 15, 37, 27), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (554, 'Obedience', 'Obedience', 'question', datetime.datetime(2013, 2, 5, 15, 37, 33), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (555, 'Perception', 'Perception', 'question', datetime.datetime(2013, 2, 5, 15, 37, 37), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (556, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 15, 37, 42), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b'),
 (557, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 15, 37, 45), datetime.datetime(2013, 10, 2, 20, 18, 7), 0, 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b')]

In [12]:
%sql SELECT TIMEDIFF(start_time,end_time) AS duration FROM exam_answers LIMIT 100;

 * mysql://studentuser:***@localhost/dognitiondb
100 rows affected.

[(datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),),
 (datetime.timedelta(days=34, seconds=82799),)]

** 질문 7 : 질문 6에서 쓴 쿼리에 Dog_Guid, start_time 및 end_time 열을 포함시키고 결과를 조사하십시오. 무언가 이상한 것이 있지 않습니까? **

In [13]:
%sql SELECT dog_guid, start_time, end_time, TIMEDIFF(end_time,start_time) AS DURATION FROM exam_answers LIMIT 100;

 * mysql://studentuser:***@localhost/dognitiondb
100 rows affected.

[('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 3, 58, 13), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 3, 58, 31), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 3, 59, 3), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 3, 59, 10), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 3, 59, 22), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 3, 59, 36), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 3, 59, 41), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 0), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 0, 16), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 0, 35), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 0, 46), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 0, 54), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 1, 1), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 1, 15), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 1, 40), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 2, 2), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 2, 30), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 3), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 3, 29), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 3, 37), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 3, 48), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 3, 56), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 4, 7), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 5, 31), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 5, 47), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 5, 57), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 6, 6), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 6, 30), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 7, 38), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 8, 58), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 9, 5), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 9, 40), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 9, 44), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 10, 3), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 10, 11), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 10, 16), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 10, 26), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 11, 12), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 11, 21), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 11, 34), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 11, 40), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 11, 54), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 12, 20), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 12, 28), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 12, 49), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 13, 5), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 13, 14), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 13, 30), datetime.datetime(2013, 10, 2, 20, 18, 6), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 13, 55), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 14, 2), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 14, 14), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 14, 22), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 14, 40), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 15, 4), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 15, 10), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 15, 38), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 15, 56), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 16, 2), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 16, 18), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 16, 27), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 16, 36), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 16, 55), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 17, 2), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 17, 20), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 17, 27), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 17, 43), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 18, 6), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 18, 15), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 18, 21), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 18, 31), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 18, 44), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 18, 50), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 19, 11), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 19, 20), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 19, 26), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 19, 32), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 19, 53), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 20, 2), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b272-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 4, 20, 24), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 35, 28), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 35, 38), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 35, 47), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 35, 54), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 36, 1), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 36, 10), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 36, 24), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 36, 33), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 36, 37), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 36, 42), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 36, 48), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 36, 54), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 36, 59), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 37, 8), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 37, 13), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 37, 20), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 37, 27), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 37, 33), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 37, 37), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 37, 42), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799)),
 ('fd27b5ba-7144-11e5-ba71-058fbc01cf0b', datetime.datetime(2013, 2, 5, 15, 37, 45), datetime.datetime(2013, 10, 2, 20, 18, 7), datetime.timedelta(days=34, seconds=82799))]

** 질문 8 : exam_answers 테이블의 테스트를 다 완료하는데 평균적으로 걸리는 시간은 얼마입니까? (어떤 데이터도 제외되지 않은 경우의 답을 구하세요. 답은 약 587분입니다) **

In [14]:
%sql SELECT * FROM exam_answers LIMIT 1;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(537, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 5, 3, 58, 13), datetime.datetime(2013, 10, 2, 20, 18, 6), 0, 'fd27b272-7144-11e5-ba71-058fbc01cf0b')]

In [20]:
%sql SELECT AVG(TIMESTAMPDIFF(minute,start_time,end_time)) FROM exam_answers;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(Decimal('586.9041'),)]

** 질문 9 : exam_answers 테이블을 보면 고객이 "Treat Warm-Up" 테스트를 완료하는데 평균적으로 몇 분 걸린 것을 알수 있습니까? (아무 데이터도 제외하지 않으면 결과는 165분이 출력되어야 합니다) **

In [21]:
%sql SELECT AVG(TIMESTAMPDIFF(minute,start_time,end_time)) FROM exam_answers WHERE test_name="Treat Warm-Up";

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(Decimal('164.9176'),)]

** 질문 10 : exam_answers 테이블에 테스트 이름은 총 몇개가 있습니까? **

In [24]:
%sql SELECT COUNT(DISTINCT(test_name)) FROM exam_answers;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(67,)]

In [25]:
%sql SELECT COUNT(DISTINCT(test_name)) FROM complete_tests;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(40,)]

** 질문 11 : exam_answers 테이블 안에서 쿼리의 기간 (Duration)열의 최소 값과 최고 값은 무엇입니까? **

In [28]:
%sql SELECT MAX(TIMESTAMPDIFF(minute,start_time,end_time)), MIN(TIMESTAMPDIFF(minute,start_time,end_time)) FROM exam_answers;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(1036673, -187)]

** 질문 12 : 마이너스 값의 기간 (Duration) 항목은 총 몇 개가 있습니까? (답은 620입니다) **

In [32]:
%sql SELECT count(*) as duration_minus_count FROM exam_answers WHERE TIMESTAMPDIFF(minute,start_time,end_time) < 0

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(620,)]

** 질문 13 : 마이너스 값이 있는 모든 기간 (Duration) 행이 있는 열을 쿼리 해보세요. 쿼리 결과에 출력된 열에 공통점이 있나요? 결과를 보면 왜 데이터 입력에 실수가 생겼는지 알수 있나요? **

In [37]:
%sql SELECT DISTINCT(step_type) FROM exam_answers;

 * mysql://studentuser:***@localhost/dognitiondb
7 rows affected.

[('question',),
 ('stopwatch',),
 ('if_question',),
 ('bark',),
 ('timer',),
 ('button',),
 (None,)]

In [35]:
%sql SELECT * FROM exam_answers WHERE TIMESTAMPDIFF(minute,start_time,end_time) < 0 LIMIT 10;

 * mysql://studentuser:***@localhost/dognitiondb
10 rows affected.

[(60, 'Empathy', 'Eye Contact Warm-up', 'question', datetime.datetime(2013, 2, 17, 20, 35, 43), datetime.datetime(2013, 2, 17, 20, 34, 43), 3, 'fd3fe18a-7144-11e5-ba71-058fbc01cf0b'),
 (558, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 18, 4, 25, 19), datetime.datetime(2013, 2, 18, 4, 24, 18), 0, 'fd3fe50e-7144-11e5-ba71-058fbc01cf0b'),
 (557, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 18, 7, 44, 9), datetime.datetime(2013, 2, 18, 7, 43, 9), 0, 'fd3fe5ea-7144-11e5-ba71-058fbc01cf0b'),
 (574, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 18, 7, 46, 14), datetime.datetime(2013, 2, 18, 7, 45, 13), 0, 'fd3fe5ea-7144-11e5-ba71-058fbc01cf0b'),
 (582, 'Shy/Boldness', 'Shy/Boldness', 'question', datetime.datetime(2013, 2, 18, 7, 47, 7), datetime.datetime(2013, 2, 18, 7, 46, 6), 0, 'fd3fe5ea-7144-11e5-ba71-058fbc01cf0b'),
 (600, 'Sociability', 'Sociability', 'question', datetime.datetime(2013, 2, 18, 7, 50, 7), datetime.datetime(2013, 2, 18, 7, 49, 7), 0, 'fd3fe5ea-7144-11e5-ba71-058fbc01cf0b'),
 (293, 'Memory', 'Two Cup Warm-up', 'question', datetime.datetime(2013, 2, 18, 13, 23, 25), datetime.datetime(2013, 2, 18, 13, 22, 23), 2, 'fd3fbd7c-7144-11e5-ba71-058fbc01cf0b'),
 (293, 'Memory', 'Two Cup Warm-up', 'question', datetime.datetime(2013, 2, 18, 13, 23, 31), datetime.datetime(2013, 2, 18, 13, 22, 28), 4, 'fd3fbd7c-7144-11e5-ba71-058fbc01cf0b'),
 (322, 'Memory', 'Memory versus Pointing', 'question', datetime.datetime(2013, 2, 18, 13, 25, 15), datetime.datetime(2013, 2, 18, 13, 24, 14), 1, 'fd3fbd7c-7144-11e5-ba71-058fbc01cf0b'),
 (322, 'Memory', 'Memory versus Pointing', 'question', datetime.datetime(2013, 2, 18, 13, 25, 30), datetime.datetime(2013, 2, 18, 13, 24, 27), 5, 'fd3fbd7c-7144-11e5-ba71-058fbc01cf0b')]

** 질문 14 : exam_answers 테이블의 모든 테스트를 푸는데 사람들이 걸리는 평균 시간을 찾아보세요. 마이너스 값 (예: -10)을 제외 하고 계산하세요 (답은 11233분 입니다) **

In [38]:
%sql SELECT AVG(TIMESTAMPDIFF(minute,start_time,end_time)) FROM exam_answers WHERE TIMESTAMPDIFF(minute,start_time,end_time) > 0;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.

[(Decimal('11233.0951'),)]